import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Children } from "react";
import Header from "./componentes/Header";
import Footer from "./componentes/Footer";
import Navbar from "./componentes/Navbar";
import SessionProvider from "./componentes/SessionProvider";
import { getServerSession } from "next-auth";
import { authConfig } from "@/lib/auth";
import {ThemeProvider } from "@/app/componentes/MaterialUI/Material";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kibo Games",
  description: "Generated by Kibo Games",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authConfig);

  return (

    <html lang="en">
      <body className={inter.className}>

        <ThemeProvider>
          <SessionProvider session={session} >
            <div className="flex flex-col min-h-screen">
              <main className="flex-grow">
              <Navbar />
              {children}
              </main>
               <Footer />
            </div>
          </SessionProvider>
        </ThemeProvider>
      </body>

    </html>
  );
}
